logFilters:
  - level: discard
    pattern: '*The darwin-* architecture*'

nodeLinker: node-modules

checksumBehavior: update

packageExtensions:
  '@chakra-ui/cli@*':
    peerDependencies:
      '@types/node': '*'
      typescript: '*'
  '@chakra-ui/toast@*':
    peerDependencies:
      '@emotion/react': '*'
      '@emotion/styled': '*'
  '@storybook/cli@*':
    peerDependencies:
      'react': '*'
      'react-dom': '*'
  '@storybook/codemod@*':
    peerDependencies:
      '@babel/preset-env': '*'
  '@storybook/addon-docs@*':
    peerDependencies:
      '@babel/core': '*'
      'webpack': '*'
  '@storybook/docs-tools@*':
    peerDependencies:
      'react': '*'
      'react-dom': '*'
  '@storybook/mdx1-csf@*':
    peerDependencies:
      '@babel/core': '*'
  '@storybook/telemetry@*':
    peerDependencies:
      'react': '*'
      'react-dom': '*'
  '@storybook/react@*':
    dependencies:
      'require-from-string': '*'
  'cosmiconfig-typescript-loader@*':
    dependencies:
      'require-from-string': '*'
      'typescript': '*'
  '@storybook/addon-essentials@*':
    dependencies:
      'require-from-string': '*'
  '@graphql-codegen/cli@*':
    dependencies:
      '@types/node': '*'
      typescript: '*'
      'ts-node': '*'
  'graphql-config@*':
    dependencies:
      '@types/node': '*'
      typescript: '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-3.1.1.cjs
