logFilters:
  - level: discard
    pattern: '*The darwin-* architecture*'

nodeLinker: node-modules

packageExtensions:
  '@chakra-ui/cli@*':
    peerDependencies:
      '@types/node': '*'
      typescript: '*'
  '@chakra-ui/toast@*':
    peerDependencies:
      '@emotion/react': '*'
      '@emotion/styled': '*'
  '@endemolshinegroup/cosmiconfig-typescript-loader@*':
    dependencies:
      typescript: ^4.5.2
  '@storybook/cli@*':
    peerDependencies:
      react: '*'
      react-dom: '*'
  '@storybook/codemod@*':
    peerDependencies:
      '@babel/preset-env': '*'
  recharts@*:
    peerDependencies:
      prop-types: ^15.6.0

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-3.1.1.cjs
