logFilters:
  - level: discard
    pattern: "*The darwin-* architecture*"

nodeLinker: node-modules

packageExtensions:
  "@chakra-ui/cli@*":
    peerDependencies:
      "@types/node": "*"
      typescript: "*"
  "@endemolshinegroup/cosmiconfig-typescript-loader@*":
    dependencies:
      typescript: ^4.5.2
  "@mdx-js/loader@*":
    peerDependencies:
      react: ^17.0.2
  "@storybook/cli@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
  "@storybook/codemod@*":
    peerDependencies:
      "@babel/preset-env": "*"
  recharts@*:
    peerDependencies:
      prop-types: ^15.6.0
  storybook-addon-performance@*:
    peerDependencies:
      react-is: ^17.0.2
  storybook-addon-swc@*:
    peerDependencies:
      webpack: ^5.68.0

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.1.1.cjs
