checksumBehavior: update

logFilters:
  - level: discard
    pattern: "*The darwin-* architecture*"

nodeLinker: node-modules

packageExtensions:
  "@chakra-ui/cli@*":
    peerDependencies:
      "@types/node": "*"
      typescript: "*"
  "@chakra-ui/toast@*":
    peerDependencies:
      "@emotion/react": "*"
      "@emotion/styled": "*"
  "@graphql-codegen/cli@*":
    dependencies:
      "@types/node": "*"
      ts-node: "*"
      typescript: "*"
  "@storybook/addon-docs@*":
    peerDependencies:
      "@babel/core": "*"
      webpack: "*"
  "@storybook/addon-essentials@*":
    dependencies:
      require-from-string: "*"
  "@storybook/cli@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
  "@storybook/codemod@*":
    peerDependencies:
      "@babel/preset-env": "*"
  "@storybook/docs-tools@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
  "@storybook/mdx1-csf@*":
    peerDependencies:
      "@babel/core": "*"
  "@storybook/react@*":
    dependencies:
      require-from-string: "*"
  "@storybook/telemetry@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
  cosmiconfig-typescript-loader@*:
    dependencies:
      require-from-string: "*"
      typescript: "*"
  graphql-config@*:
    dependencies:
      "@types/node": "*"
      typescript: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.3.0.cjs
