logFilters:
  - level: discard
    pattern: '*The darwin-* architecture*'

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-3.1.1.cjs

packageExtensions:
  recharts@*:
    peerDependencies:
      prop-types: ^15.6.0
  '@chakra-ui/cli@*':
    peerDependencies:
      '@types/node': '*'
      typescript: '*'
  '@storybook/cli@*':
    peerDependencies:
      react: '*'
      react-dom: '*'
  '@storybook/codemod@*':
    peerDependencies:
      '@babel/preset-env': '*'
  '@storybook/addon-docs@*':
    peerDependencies:
      '@babel/core': '*'
      'webpack': '*'
  '@storybook/docs-tools@*':
    peerDependencies:
      'react': '*'
      'react-dom': '*'
  '@storybook/mdx1-csf@*':
    peerDependencies:
      '@babel/core': '*'
  '@storybook/telemetry@*':
    peerDependencies:
      'react': '*'
      'react-dom': '*'
  '@endemolshinegroup/cosmiconfig-typescript-loader@*':
    dependencies:
      'typescript': '^4.5.2'
