logFilters:
  - level: discard
    pattern: '*The darwin-* architecture*'

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-3.1.1.cjs

packageExtensions:
  recharts@*:
    peerDependencies:
      prop-types: ^15.6.0
  storybook-addon-performance@*:
    peerDependencies:
      react-is: ^17.0.2
  storybook-addon-swc@*:
    peerDependencies:
      webpack: ^5.68.0
  '@chakra-ui/cli@*':
    peerDependencies:
      '@types/node': '*'
      typescript: '*'
  '@mdx-js/loader@*':
    peerDependencies:
      react: ^17.0.2
  '@storybook/cli@*':
    peerDependencies:
      react: '*'
      react-dom: '*'
  '@storybook/codemod@*':
    peerDependencies:
      '@babel/preset-env': '*'
  '@endemolshinegroup/cosmiconfig-typescript-loader@*':
    dependencies:
      'typescript': '^4.5.2'
